import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Card from '../components/card'

export default function Home({pokemon}) {
  console.log(pokemon);
  return (
    <body>
      <header className={styles.topBar}>
        <Head>
          <title>Pokedex</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <a className={styles.camera}/>
        <a className={styles.redButton}/>
        <a className={styles.yellowButton}/>
        <a className={styles.greenButton}/>
        <div className={styles.searchArea}>
          <input type="textBox" placeholder="Search" name="pesquisa" id="searchBar" className={styles.searchBar}></input>
          <input type="button" value="Ok" name="searchButton" onClick="pesquisar()" className={styles.searchButton}></input>
        </div>
      </header>

      <main className={styles.lista}>
        <Card/>
        <Card/>
        <Card/>
        <Card/>
        <Card/>
        <Card/>
        <Card/>
        <Card/>
        <Card/>
        <Card/>
      </main>
      
    </body>
  )
}

export async function getStaticProps(context){
  try {
    const res = await fetch('https://pokeapi.co/api/v2/pokemon?limit=151');
    const {results} = await res.json();
    const pokemon = results.map((result, index) => {
      const formatedIndex = ("00" + (index + 1)).slice(-3);
      const image = `https://assets.pokemon.com/assets/cms2/img/pokedex/full/${formatedIndex}.png`
      return {
        ...result,
        image,
      };
    })
    return {
      props: {pokemon},
    };
  } catch (err) {
    console.error(err);
  };
}