import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Card from '../components/card'

export default function Home() {
  return (
    <body>
      <div className={styles.topBar}>
        <Head>
          <title>Pokedex</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <a className={styles.camera}/>
        <a className={styles.redButton}/>
        <a className={styles.yellowButton}/>
        <a className={styles.greenButton}/>
        <div className={styles.searchArea}>
          <input type="textBox" placeholder="Search" name="pesquisa" id="searchBar" className={styles.searchBar}></input>
          <input type="button" value="Ok" name="searchButton" onclick="pesquisar()" className={styles.searchButton}></input>
        </div>
      </div>
      <div className={styles.lista}>
        <Card/>
      </div>
      
    </body>
  )
}
